services:
  wakatime-exporter:
    depends_on:
      - wakatime-database
    container_name: wakatime-exporter
    build: .
    env_file:
      - .env
    networks:
      - wakatime

  wakatime-database:
    container_name: wakatime-database
    image: mysql:8.0
    ports:
      - "3360:3306"
    hostname: wakatime-database
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: wakatime
    command:
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - wakatime

networks:
  wakatime:
    driver: bridge

volumes:
    mysql_data: